version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: >+
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn moneyTracker.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10"
            
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=moneyTracker.settings.prod
      - DJANGO_CORS_ALLOWED_ORIGINS=${DJANGO_CORS_ALLOWED_ORIGINS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    image: nginx:latest
    links:
      - app

volumes:
  dev-db-data:
